### PR TITLE
A little change for back button style consistency

### PR DESCRIPTION
**Pull request by ybw0014**

### CODE REVIEW

**Comment by Sefiraat** [comment]
@ybw0014 looks like your autopull killed this PR as it's from Master. Sorry I didn't get around to this, you're welcome to PR again - this is my fault though, sorry.

**Comment by ybw0014** [comment]
bruh

**Comment by ybw0014** [comment]
I think JustAHuman has already done this, so I don't need to create a new PR.

**Comment by Sefiraat** [comment]
Either way, it's mb, sorry :)

**Pull request closed without merging**
